@startuml
'https://plantuml.com/class-diagram'

interface ReadOnlyDao

+class App {
    +PromiseHistoryClient getPromiseHistoryClient()
    +GetPromiseHistoryByOrderIdActivity getPromiseHistoryByOrderIdActivity()
    +OrderDao getOrderDao()
    +PromiseDao getPromiseDao()
    +OrderManipulationAuthorityClient getOrderManipulationAuthorityClient()
    +DeliveryPromiseServiceClient getDeliveryPromiseServiceClient()
    +OrderManipulationAuthority getOrderManipulationAuthority()
    +DeliveryPromiseService getDeliveryPromiseService()
    +OrderDatastore getOrderDatastore()
}

+class Order {
    +String orderId
    +getters()
    +setters()
    +{static} class Builder()
}

+class OrderItem {
    -String customerOrderItemId
    -String orderId
    +getters()
    +setters()
    +{static} class Builder()
}

+class Promise {
    -String customerOrderItemId
    -ZonedDateTime promiseLatestShipDate
    +getters()
    +setters()
    +{static} class Builder()
}

+class PromiseHistory {
    -Order order
    -List<Promise> promises
    +PromiseHistory(Order order)
    +Order getOrder()
    +void addPromise(Promise newPromise)
    +List<Promise> getPromises()
}

+class PromiseHistoryClient {
    --fields--
    -GetPromiseHistoryByOrderIdActivity getPromiseHistoryByOrderIdActivity
    --methods--
    +PromiseHistoryClient(GetPromiseHistoryByOrderIdActivity getPromiseHistoryByOrderIdActivity)
    +PromiseHistory getPromiseHistoryByOrderId(String orderId)
}

+class GetPromiseHistoryByOrderIdActivity {
    --fields--
    -ReadOnlyDAO orderDao
    -ReadOnlyDAO promiseDao
    --methods--
    +GetPromiseHistoryByOrderIdActivity(ReadOnlyDAO orderDao, ReadOnlyDAO PromiseDao)
    +GetPromiseHistoryByOrderId(String orderId)
}

+class OrderDao {
    --fields--
    -OrderManipulationAuthorityClient
    --methods--
    +OrderDAO(OrderManipulationAuthorityClient client)
    +Order get(String orderId)
    +OrderItem convertToOrderItem(OrderResultItem orderResultItem)
}

+class PromiseDao {
    --fields--
    -DeliveryPromiseServiceClient dpsclient
    -OrderManipulationAuthorityClient omaClient
    --methods--
    +PromiseDAO(DPSC dpsClient, OMAC omaClient)
    +List<Promise> get(String customerOrderItemId)
    -ZonedDateTime getDeliveryDateForOrderItem(String customerOrderItemId)
}

+class OrderManipulationAuthorityClient {
    --fields--
    -OrderManipulationAuthority omaService
    --methods--
    +OrderManipulationAuthorityClient(OrderManipulationAuthority service)
    +OrderResult getCustomerOrderByOrderId(String orderId)
    +OrderResultItem getCustomerOrderItemByOrderItemId(String orderItemId)
}

+class DeliveryPromiseServiceClient {
    --fields--
    -DeliveryPromiseService dpService
    --methods--
    +DeliveryPromiseServiceClient(DeliveryPromiseService dpService)
    +Promise getDeliveryPromiseByOrderItemId(String (String customerOrderItemId)
}







PromiseHistoryClient o-- GetPromiseHistoryByOrderIdActivity
GetPromiseHistoryByOrderIdActivity o-- PromiseDao
GetPromiseHistoryByOrderIdActivity o-- OrderDao
PromiseDao o-- DeliveryPromiseServiceClient
PromiseDao o-- OrderManipulationAuthorityClient
OrderDao o-- OrderManipulationAuthorityClient
PromiseHistory o-- Order
PromiseHistory o-- Promise
Order o-- OrderItem
OrderDao o-- ReadOnlyDao

@enduml